ADFHOST2302="http://csdnim.qtmojo.com";
ADFCID2302=63;
ADFBID2302=2302;
ADFLOC='CNBJ0000';
ADFUSER2302="http://csdnim.qtmojo.com/c?d=csdnim&i=z63,10404730,2302,11569&rf=http%3A%2F%2Fbbs.csdn.net%2Ftopics%2F390901299&a=dICsLsBkx2chD2A5yG71qyUaQWgN&u=";
ALLYESID4="CG3q21K7o16BHIk2gFj";
ADFPGC="2,8,63,0,3014,2302,11569,10404730";

document.write("<script type='text/javascript'>\n");
document.write("var googletag = googletag || {};\n");
document.write("googletag.cmd = googletag.cmd || [];\n");
document.write("(function() {\n");
document.write("var gads = document.createElement('script');\n");
document.write("gads.async = true;\n");
document.write("gads.type = 'text/javascript';\n");
document.write("var useSSL = 'https:' == document.location.protocol;\n");
document.write("gads.src = (useSSL ? 'https:' : 'http:') + \n");
document.write("'//www.googletagservices.com/tag/js/gpt.js';\n");
document.write("var node = document.getElementsByTagName('script')[0];\n");
document.write("node.parentNode.insertBefore(gads, node);\n");
document.write("})();\n");
document.write("</Scr"+"ipt>\n");
document.write("\n");
document.write("<div id='div-gpt-ad-1430968810821-0'>\n");
document.write("<script type='text/javascript'>\n");
document.write("googletag.cmd.push(function() {\n");
document.write("googletag.defineSlot('/8456/IDG.CN_B2B_csdn.net', [728, 90], 'div-gpt-ad-1430968810821-0')\n");
document.write(".addService(googletag.pubads())\n");
document.write(".setTargeting(\"category\",\"bbs\");\n");
document.write("googletag.enableServices();\n");
document.write("googletag.display('div-gpt-ad-1430968810821-0');\n");
document.write("});\n");
document.write("</Scr"+"ipt>\n");
document.write("</div>");

